<?php

use Illuminate\Database\Seeder;


class ClasificadoresSeeder extends Seeder
{
    public function run()
    {//CLASIFICADOR


      $datos = [
      [ 'id_clasificador'=>'1', 'codigo'=>'30000','clasificador'=>'Materiales y Suministros', 'descripcion'=>'Gastos destinados a la adquisición de bebidas y productos alimenticios, manufacturados o no, incluye animales vivos para consumo, aceites, grasas animales y vegetales, forrajes y otros alimentos para animales; además, comprende productos agrícolas, ganaderos, de silvicultura, caza y pesca. Comprende madera y productos de este material.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31000','clasificador'=>'Alimentos y Productos Agroforestales ', 'descripcion'=>'Gastos destinados al pago de comida y bebida en establecimientos hospitalarios, penitenciarios, de orfandad, cuarteles, aeronaves, y para el personal de seguridad según convenio interinstitucional; incluye pago de refrigerio: al personal permanente, eventual y consultores individuales de línea de cada entidad, por procesos electorales, emergencias y/o desastres naturales; así como  almuerzos o cenas de trabajo según disposición legal, desayuno escolar y otros relacionados de acuerdo a normativa vigente. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31100','clasificador'=>'Alimentos y Bebidas para Personas, Desayuno Escolar y Otros', 'descripcion'=>'Gastos destinados a la adquisición de bebidas y productos alimenticios, manufacturados o no, incluye animales vivos para consumo, aceites, grasas animales y vegetales, forrajes y otros alimentos para animales; además, comprende productos agrícolas, ganaderos, de silvicultura, caza y pesca. Comprende madera y productos de este material.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31110','clasificador'=>'Gastos por Refrigerios al personal permanente', 'descripcion'=>'Gastos por Refrigerios al personal permanente, eventual y consultores individuales de línea de las Instituciones Públicas. Incluye pago por refrigerios al personal de seguridad de la Policía Boliviana, según convenio interinstitucional. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31120','clasificador'=>'Gastos por Alimentación y Otros Similares.', 'descripcion'=>'Gastos por Alimentación y Otros Similares. Incluye los efectuados en reuniones, seminarios y otros eventos; así como los gastos por dotación de víveres a la Policía Boliviana y Fuerzas Armadas.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31130','clasificador'=>'Alimentación Complementaria Escolar', 'descripcion'=>'Alimentación Complementaria Escolar', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31140','clasificador'=>'Alimentación Hospitalaria, Penitenciaria, Aeronaves y Otras Específicas', 'descripcion'=>'Alimentación Hospitalaria, Penitenciaria, Aeronaves y Otras Específicas', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31150','clasificador'=>'Alimentos y Bebidas para la atención de emergencias y desastres naturales.', 'descripcion'=>'Alimentos y Bebidas para la atención de emergencias y desastres naturales.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31200','clasificador'=>'Alimentos para Animales', 'descripcion'=>'Gastos destinados a la adquisición de forrajes y otros alimentos para animales de propiedad de instituciones públicas; alimentación de los animales de propiedad del Ejército y de la Policía Boliviana, parques zoológicos, laboratorios de experimentación y otros similares.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'31300','clasificador'=>'Productos Agrícolas, Pecuarios y Forestales ', 'descripcion'=>'Gastos para la adquisición de granos básicos, frutas y flores silvestres, goma, caña, semillas y otros productos agroforestales y agropecuarios en bruto; además,  gastos poconcepto de adquisición de maderas de construcción, puertas, ventanas, vigas, callapos,durmientes manufacturados o no, y todo otro producto proveniente de esta rama,incluido carbón vegetal. Incluye gastos por la compra de ganado y otros animales vivos,destinados al consumo o para usos industriales y científicos; incluye productos derivadode los mismos, como ser leche, huevos, lana, miel, pieles y otros. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32000','clasificador'=>' Productos de Papel, Cartón e Impresos', 'descripcion'=>'Gastos destinados a la adquisición de papel y cartón en sus diversas formas y clases; libros y revistas, textos de enseñanza, compra y suscripción de periódicos.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32100','clasificador'=>'Papel', 'descripcion'=>'Gastos destinados a la adquisición de papel de escritorio y otros.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32200','clasificador'=>'Productos de Artes Graficas', 'descripcion'=>'Gastos para la adquisición de productos de artes gráficas y otros relacionados. Incluye gastos destinados a la adquisición de artículos hechos de papel y cartón.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32300','clasificador'=>'Libros, Manuales y Revistas', 'descripcion'=>'Gastos destinados a la adquisición de libros, manuales y revistas para bibliotecas y oficinas.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32400','clasificador'=>'Textos de Enseñanza', 'descripcion'=>'Gastos destinados a la compra de libros para uso docente.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'32500','clasificador'=>'Periodicos y Boletines', 'descripcion'=>'Gastos para la compra y suscripción de periódicos y boletines, incluye gacetas oficiales.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'33000','clasificador'=>'Textiles y Vestuario', 'descripcion'=>'Gastos para la compra de ropa de trabajo, vestuario, uniformes, adquisición de calzados, hilados, telas de lino, algodón, seda, lana, fibras artificiales y tapices, alfombras, sábanas, toallas, sacos de fibras y otros artículos conexos de cáñamo, yute y otros similares. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'33100','clasificador'=>'Hilados, Telas y Fibras y Algodón', 'descripcion'=>'Gastos destinados para la compra de hilados y telas de lino, algodón, seda, lana y fibrasartificiales, no utilizados aún en procesos de confección.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'33200','clasificador'=>'Confecciones Textiles', 'descripcion'=>'Gastos destinados a la adquisición de tapices, alfombras, sábanas, toallas, sacos de fibras, colchones, carpas, cortinas y otros textiles similares.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'33300','clasificador'=>'Prendas de Vestir', 'descripcion'=>'Gastos destinados a la adquisición de uniformes, vestimenta de diversos tipos, ropa de trabajo, distintivos y accesorios, independientemente del material de fabricación y otras de seguridad industrial de trabajo establecidas por disposiciones en vigencia.  ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'33400','clasificador'=>'Calzados ', 'descripcion'=>'Gastos destinados a la compra de calzados o zapatos complementarios de uniformes y los de uso exclusivo de servidores públicos que, por razones de seguridad industrial de trabajo establecidas por disposiciones en vigencia.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34000','clasificador'=>'Combustibles, Productos Químicos, Farmacéuticos y Otras Fuentes de Energía ', 'descripcion'=>'Gastos destinados a la compra de combustibles, lubricantes, energía eléctrica, productos químicos y farmacéuticos, llantas, neumáticos y otras similares.Se incluye gastos por compra de cueros en sus distintos tipos (excepto vestimenta) elaborados o semi elaborados en forma de  tientos, correas, suelas y demás formas empleadas en distintos usos, cauchos en sus distintas formas de producción (planchas, trozos o bajo forma de caños), tubos, caucho en bruto; gastos por compra de cemento, cal y productos elaborados con arcilla, vidrio, loza, porcelana, cemento, asbesto, yeso y plástico para fines de uso o consumo, producción, mantenimiento o construcción de obras; gastos por la compra de  productos siderúrgicos férricos y no férricos, de estructuras metálicas acabadas, herramientas menores, material y equipo militar y otros productos metálicos. Comprende adicionalmente recursos para la adquisición de minerales sólidos, minerales metálicos y no metálicos.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34100','clasificador'=>'Combustibles, Lubricantes, Derivados y otras Fuentes de Energía  ', 'descripcion'=>'Gastos para la adquisición de petróleo crudo y parcialmente refinado, gasolina, kerosene, alcohol, aceites, grasas, fuel-oil, diesel, alquitrán, energía eléctrica y otros similares, como gas y cemento asfáltico. Se excluye la compra de leña y carbón. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34110','clasificador'=>'Combustibles, Lubricantes y Derivados para consumo', 'descripcion'=>'Combustibles, Lubricantes y Derivados para consumo', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34120','clasificador'=>'Combustibles, Lubricantes y Derivados para comercialización', 'descripcion'=>'Combustibles, Lubricantes y Derivados para comercialización', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34130','clasificador'=>'Energía Eléctrica para Comercialización  ', 'descripcion'=>'Energía Eléctrica para Comercialización  ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34200','clasificador'=>'Productos Químicos y Farmacéuticos ', 'descripcion'=>'Gastos para la adquisición de compuestos químicos, tales como ácidos, sales, bases industriales, salitres, calcáreos, pinturas, colorantes, pulimentos; abonos y fertilizantes destinados a labores agrícolas; insecticidas, fumigantes y otros utilizados en labores agropecuarias; medicamentos e insumos para hospitales, clínicas, policlínicas y dispensarios, incluyendo productos básicos para botiquines y los utilizados en veterinaria. Además de los insumos requeridos en la construcción, remodelación y mantenimiento de activos fijos y otros materiales químicos, anticongelantes. ', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34300','clasificador'=>'Llantas y Neumáticos', 'descripcion'=>'Gastos destinados a la compra de aros, llantas y neumáticos para utilización en los equipos de tracción, transporte y elevación.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],
      [ 'id_clasificador'=>'1', 'codigo'=>'34400','clasificador'=>'Productos de Cuero y Caucho', 'descripcion'=>'Gastos destinados a la compra de cueros, pieles, curtidos y sin curtir; maletines, portafolios y otros artículos confeccionados con cuero; además de artículos elaborados con caucho, excepto prendas de vestir, llantas y cámaras de aire.', 'id_usuario'=>'1', 'id_gestion'=>'1' ],


        ];

      foreach($datos as $est){
          \App\Clasificadores::create($est);
      }

    }
}
